builds:
  -
    goos:
      - linux
      - darwin
      #- windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

    binary: hades

