version: 1

plans:
  setup-caddy-repo:
    description: Setup Caddy repository with dearmored GPG key
    targets:
      - production

targets:
  production:
    inventory: ./inventory/production.hades.yaml
    jobs:
      - setup-gpg-keys

jobs:
  setup-gpg-keys:
    local: false
    actions:
      # Download ASCII-armored GPG key and convert to binary format
      # This is equivalent to: curl -1sLf <url> | gpg --dearmor -o <output>
      - gpg:
          src: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
          path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          dearmor: true
          mode: 0644

      # Add Caddy repository with the dearmored GPG key
      - run: |
          echo "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/caddy-stable.list

      # Update apt cache
      - run: sudo apt-get update

      # Install Caddy
      - run: sudo apt-get install -y caddy
