version: 1

# Example: Using guards to conditionally install Caddy web server
# The guard ensures Caddy is only installed if it's not already present

plans:
  install-caddy:
    description: Install Caddy web server (only if not already installed)
    steps:
      - name: Install Caddy
        job: install-caddy-job
        targets:
          - webservers

targets:
  webservers:
    inventory: ./inventory/production.hades.yaml

jobs:
  install-caddy-job:
    # Guard: Only run this job if Caddy is NOT installed
    # Success (exit 0) = continue with job
    # Failure (exit non-zero) = skip job
    guard:
      if: "! which caddy"  # Negated - returns 0 if caddy NOT found

    actions:
      # Download and install GPG key for Caddy repository
      - gpg:
          src: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
          path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          dearmor: true
          mode: 0644

      # Add Caddy repository to apt sources
      - run: |
          echo "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/caddy-stable.list

      # Update apt cache
      - run: sudo apt-get update

      # Install Caddy
      - run: sudo apt-get install -y caddy

      # Verify installation
      - run: caddy version
